services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - 8080:3003
    environment:
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - ./frontend:/app:delegated
      - /app/node_modules
    # Override the image to use local build instead of pulling from registry 