services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: asaleem67/frontend:latest
    container_name: frontend
    ports:
      - 8080:80
    depends_on:
      - api

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    image: asaleem67/api:latest
    container_name: api
    ports:
      - 3000:3000
    environment:
      - PORT=3000
      - DB_HOST=database
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=mysecretpassword
      - DB_NAME=bookstore
    depends_on:
      - db-seeder

  database:
    image: postgres:15-alpine
    container_name: database
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=mysecretpassword
      - POSTGRES_DB=bookstore

  db-seeder:
    build:
      context: ./db
      dockerfile: Dockerfile
    container_name: db-seeder
    depends_on:
      - database
    environment:
      - PGPASSWORD=mysecretpassword
    restart: "no"

